/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author Mary Jhezl
 */
public class AddStudent extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    public AddStudent() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        profileTXT1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        programTXT = new javax.swing.JLabel();
        nameTXT = new javax.swing.JLabel();
        srcodeTXT = new javax.swing.JLabel();
        srcodeFld = new javax.swing.JTextField();
        nameFld = new javax.swing.JTextField();
        addressTXT = new javax.swing.JLabel();
        addressFld = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        programcombobox = new javax.swing.JComboBox<>();
        imagelbl = new javax.swing.JLabel();
        imagechooserbtn = new javax.swing.JButton();
        emailTXT = new javax.swing.JLabel();
        emailFld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(152, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        profileTXT1.setBackground(new java.awt.Color(255, 255, 255));
        profileTXT1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        profileTXT1.setForeground(new java.awt.Color(255, 255, 255));
        profileTXT1.setText("Add Student");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(profileTXT1)
                .addContainerGap(962, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileTXT1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1120, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 841));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        programTXT.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        programTXT.setText("Program:");
        jPanel1.add(programTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        nameTXT.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        nameTXT.setText("Name:");
        jPanel1.add(nameTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        srcodeTXT.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        srcodeTXT.setText("SR-Code:");
        jPanel1.add(srcodeTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));
        jPanel1.add(srcodeFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 160, 150, -1));
        jPanel1.add(nameFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 340, -1));

        addressTXT.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        addressTXT.setText("Address:");
        jPanel1.add(addressTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        addressFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFldActionPerformed(evt);
            }
        });
        jPanel1.add(addressFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 340, -1));

        saveBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 730, 91, -1));

        cancelBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 730, 91, -1));

        programcombobox.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        programcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", " ", " ", " ", " " }));
        jPanel1.add(programcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 150, 30));

        imagelbl.setBackground(new java.awt.Color(102, 102, 102));
        imagelbl.setForeground(new java.awt.Color(255, 255, 204));
        imagelbl.setOpaque(true);
        jPanel1.add(imagelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 200, 190));

        imagechooserbtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        imagechooserbtn.setText("Choose Image");
        imagechooserbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagechooserbtnActionPerformed(evt);
            }
        });
        jPanel1.add(imagechooserbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 140, 30));

        emailTXT.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        emailTXT.setText("Email:");
        jPanel1.add(emailTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, -1, -1));
        jPanel1.add(emailFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 340, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed

    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void imagechooserbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagechooserbtnActionPerformed
       
    }//GEN-LAST:event_imagechooserbtnActionPerformed

    private void addressFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressFld;
    private javax.swing.JLabel addressTXT;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField emailFld;
    private javax.swing.JLabel emailTXT;
    private javax.swing.JButton imagechooserbtn;
    private javax.swing.JLabel imagelbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nameFld;
    private javax.swing.JLabel nameTXT;
    private javax.swing.JLabel profileTXT1;
    private javax.swing.JLabel programTXT;
    private javax.swing.JComboBox<String> programcombobox;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField srcodeFld;
    private javax.swing.JLabel srcodeTXT;
    // End of variables declaration//GEN-END:variables
}
